services:
  node-app:
    image: node:trixie-slim
    working_dir: /app
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "
        npm install express &&
        npm start
      "

volumes: {}